---
- name: Install Postgres
  hosts: emailcongress-db
  become: yes
  roles:
    - role: roles/postgres-apt-ppa
      distro_version_name: trusty
      signing_key: ACCC4CF8
    - role: common-roles/common
      hostname: "db.{{hostname}}"
    - role: common-roles/postgres
      pgversion: 9.4
      dbuser: "emailcongress"
      dbpassword: "test"
      dbname: "emailcongress"
    - role: common-roles/postgres
      pgversion: 9.4
      dbuser: "phantom_dc"
      dbpassword: "test"
      dbname: "phantom_dc"
